[build]
  command = "echo 'No build required for Python functions'"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"

[functions]
  external_node_modules = ["pandas", "numpy"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
