[build]
  command = "echo 'No build required for Python functions'"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
